version: '3'

services:
  web:
    build:
      target: development
    command: npm run docker:dev 
    labels:
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
    ports:
      # Note: When using traefik no need to use this, even locally.
      # The reason is that it will get auto mapped from exposed ports..
      # .. and traefik just picks it up like magic
      # (but we need to set the network correclty, see bellow)
      - "${BIND_PORT}:${BIND_PORT}"
    volumes:
      - .:/app
#     networks:
#       - proxy
  mongo:
    # We setting up a Single Replica node, to allow transactions from Prisma
    image: bitnami/mongodb:latest
    restart: unless-stopped
    container_name: mongo-${NODE_ENV:-dev}
    # We only map these, in case we wanto to run the project locally
    # If we going to use Docker even during dev, we can remove these
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_USER=${MONGODB_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${PROJECT_NAME}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
    volumes:
      - mongodbdata:/data/db
#     networks:
#       - proxy

volumes:
  mongodbdata:
    name: "${PROJECT_NAME}-mongo"

# networks:
#   proxy:
#     name: traefik-proxy
#     external: true

