version: '3'

services:
  web:
    build:
      target: production
    command: pm2-runtime pm2.config.json
    labels:
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=letsEncryptResolver"
    networks:
      - proxy

networks:
  proxy:
    name: traefik-proxy
    external: true

